name: Solar System Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - "features/*"

jobs:
  unit-testing:
    name: Unit testing
    runs-on: ubuntu-latest
    env:  # Set environment variable at the job level
      MONGO_URI: ${{ secrets.MONGO_URI }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
          
      - name: Setup Node.js Version - 20
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install
          
      - name: Unit testing
        run: npm test
